# GitHub Action metadata file.
# For details, see:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/metadata-syntax-for-github-actions
---
name: Jekyll Builder for GitHub Pages
description: >
    Build Jekyll sites using the official Jekyll `builder` Docker image,
    then optionally deploy to GitHub Pages.

inputs:

    #
    # Repository secrets needed for authentication.
    #
    secret_gh_pages_api_token:
        required: false
        description: If deploying to GitHub Pages, set this to the value of a GitHub Personal Access Token granted the `public_repo` and `repo_deployment` scopes.

    #
    # Customization options available to the action's user.
    #
    pre_build_commands:
        required: false
        description: >
            Commands to run prior to build and deploy. Useful for
            ensuring build dependencies are up to date. For example,
            use `gem install bundler` to update Bundler to the latest
            available version.

    post_build_commands:
        required: false
        description: >
            Commands to run after the Jekyll build and before
            a deploy.

    jekyll_build_opts:
        required: false
        description: >
            Extra options to pass to `jekyll build`.

    gh_pages_publishing_source:
        required: false
        description: >
            Branch name to which this action will commit the
            result of the Jekyll build. Ignored for User or
            Organization repositories since only `master`
            can be used as a publishing source for those
            repos. This is automatically detected if you
            already have GitHub Pages publishing source
            defined in your repository settings.

    git_commit_message:
        required: false
        description: >
            The commit message to use when commtting back to
            your GitHub Pages branch.
        default: >
            Auto-commit Jekyll build from Jekyll Builder
            for GitHub Pages Action.

# TODO
#outputs:
#    action_gh_pages_build_status:
#        description: The HTTP status code of the response to the API request initiating the GitHub Pages deployment.

runs:
    using: docker
    image: Dockerfile
    env:
        # Jekyll Docker will use a non-root user by default for some
        # important tasks, like building the Jekyll site. This is not
        # compatible with GitHub Actions, which requires container
        # actions to run as the Docker default user (`root`). So, we
        # set these environment variables to tell Jekyll Docker to run
        # `jekyll` as `root` for all operations.
        JEKYLL_GID: 0
        JEKYLL_UID: 0

        # When using the `github-pages` Gem, this environment variable
        # is needed for a successful build when the same information
        # is missing from the repository's `_config.yml` file.
        PAGES_REPO_NWO: ${{ github.repository }}

branding:
    icon: upload-cloud
    color: gray-dark
